name: Build the game
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: StandaloneWindows64
    - uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: StandaloneOSX
    - uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: StandaloneLinux64
    - uses: actions/upload-artifact@v2
      with:
        name: windows-${{ github.sha }}
        path: build/StandaloneWindows64
    - uses: actions/upload-artifact@v2
      with:
        name: mac-${{ github.sha }}
        path: build/StandaloneOSX
    - uses: actions/upload-artifact@v2
      with:
        name: linux-${{ github.sha }}
        path: build/StandaloneLinux64
