name: Build the game
on:
  push:
    branches:
      - main
jobs:
  build-windows:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Cache libraries
      uses: actions/cache@v2
      env:
        cache-name: cache-library
      with:
        path: Library
        key: nubisoft-windows
        restore-keys: |
          nubisoft-
    - name: Build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: StandaloneWindows64
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: windows-${{ github.sha }}
        path: build/StandaloneWindows64
  build-mac:
    name: Mac Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Cache libraries
      uses: actions/cache@v2
      env:
        cache-name: cache-library
      with:
        path: Library
        key: nubisoft-mac
        restore-keys: |
          nubisoft-
    - name: Build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: StandaloneOSX
    - name: Add executable bit to binary
      run: chmod +x build/Standalone/StandaloneOSX.app/Contents/MacOS/Peons
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: mac-${{ github.sha }}
        path: build/StandaloneOSX
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Cache libraries
      uses: actions/cache@v2
      env:
        cache-name: cache-library
      with:
        path: Library
        key: nubisoft-linux
        restore-keys: |
          nubisoft-
    - name: Build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: StandaloneLinux64
    - name: Add executable bit to binary
      run: chmod +x build/StandaloneLinux64/StandaloneLinux64
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: linux-${{ github.sha }}
        path: build/StandaloneLinux64
